export class ChangeProduct{
    id:number
    name?:string
    price?:number
    discount?:number
    description?:string
    categoryId?:number
    properties?:Array<{
        id?:number
        key:string
        value:string
    }>
    sizes?:Array<{
        id?:number
        value:string
    }>
    colors?:Array<{
        id?:number
        value:string
    }>
}